# Generated by Django 4.1.13 on 2024-12-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_appuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='division',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
