# Generated by Django 4.1.13 on 2024-12-02 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_location_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='location',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='app.location'),
        ),
    ]
